### PR TITLE
Add Catalan translation

### PR DESCRIPTION
**Pull request by ericmp33**

### CODE REVIEW

**Comment by ericmp33** [comment]
Related issue - #311

**Comment by emoacht** [comment]
Thanks for quick PR.
I have a question on the culture-locale. On my PC, I cannot find "ca-CA" from all supported cultures. Could you check what culture-locale is used on your PC? It can be checked as described in https://stackoverflow.com/a/864524/3137337

Then, regarding "Moure els controls alhora" and "Habilitar moure els controls alhora", I just changed their original English languages by 3da7b58848165afe7aca9a74e309024c304eb210 
So, could you translate them again?

**Comment by ericmp33** [comment]
It is probably ca-ES, but we never say it that way. We say Catalan from Catalonia, not Catalan from Spain. I just changed the file name from `Resources.ca-CA.resx` to `Resources.ca.resx`, but yeah you can name it however you feel it better.

On the other hand okay, I updated a translation.

**Comment by emoacht** [comment]
Thanks.
Regarding the culture-locale, I will change it.

Regarding the translation, is it safe to change "Habilitar moure els controls alhora" to "Habilitar canviar la brillantor alhora" as well?

**Comment by ericmp33** [comment]
Yes, is it safe. Feel free to ping me if you update/add more translations.

**Comment by emoacht** [comment]
Thanks for the confirmation.
I will merge it and then work on it.

**Pull request merged**
