### PR TITLE
Add support for NonStandard Monitor like Q2790PC

### PR DESCRIPTION
**Pull request by CC0126**
Add support for NonStandard Monitor like Q2790PC that have multiple ports, some of the ports support DDC/CI but returns bad VCP codes.

### CODE REVIEW

**Comment by CC0126** [comment]
Hello, I am a big fan of your software, I have been using it for 1.5 years.
At first I only used it to control my AOC Q2790PQ, it had no problems, but after I replaced a monitor AOC Q2790PC, the software did not work properly.
After many searches, I found the open source address of your software, downloaded its source code, and studied it.
After I tested DDC-Control, AOC iMenu, FreeMonitorManager, I found the problem.
This new monitor has multiple interfaces (such as HDMI, DP, USB-C), the VCP value of the USB-C interface returns to normal, but HDMI returns garbled characters, which makes the software unable to obtain whether the display actually supports DDC /CI command, which hinders the work of the software.
I can get the actual brightness by judging that the VCP has a response but cannot be resolved. To determine whether the monitor supports DDC/CI non-standard, just like FreeMonitorManager.
Now he works fine on my monitor. 
Because I like this software very much, so I decided to submit these codes to you,to help others to control their NonStandard monitors.
Thank you for your efforts. Best wishes   CC0126

**Comment by emoacht** [comment]
Thanks for the PR.
Could you open an issue attached with probe.log on Q2790PC and explain your intension?
I will not merge as it is.

**Comment by CC0126** [comment]
Thank you, I will dump a log to you and open a new issue

**Comment by emoacht** [comment]
As #270 solved this issue, this PR is closed.

**Pull request closed without merging**
