### PR TITLE
Added italian localization

### PR DESCRIPTION
**Pull request by GhostyJade**
With this pull request I've added italian to a new Resource file.
It's not 100% accurate since I could't understand every single context related to some lines.
Hope it helps

### CODE REVIEW

**Comment by emoacht** [comment]
Thanks for PR!
If you have a difficultly in understanding the meaning of a particular item or message, I can explain it. Could you specify such a item or message?

**Comment by GhostyJade** [comment]
The unclear one are
<HTML>
<BODY>
<TABLE><TR><TD>DeferChange</TD><TD>Defer change until stopped</TD></TR><TR><TR><TD>EnableUnison</TD><TD>Enable moving in unison</TD></TR></TABLE>

</BODY>
</HTML>
What are the context/actions where those are used?
Thanks

**Comment by emoacht** [comment]
Okay. Let me explain.

__DeferChange:__ When a user holds a monitor's slider thumb and move it to adjust the brightness, this app will change the actual brightness of the monitor seamlessly at short intervals. If this setting is enabled, this app will differ the actual change of brightness until the thumb is stopped. In other words, this app will wait to change the actual brightness until the user releases the thumb.

__EnableUnison:__ This app has a function called "move in unison" which allow a user to change the brightness of a set of monitors synchronously. If this settings is enabled, a button will be shown at the right-top corner of each monitor's slider. This button can be user to add/remove the monitor to a set of monitors to be targeted by this function.

I hope this will help.

**Comment by GhostyJade** [comment]
@emoacht thanks for the help. I've fixed the DeferChange string

**Comment by GhostyJade** [comment]
I don't have any other commit to upload, if you need you can close this pull request

**Comment by emoacht** [comment]
I will take care of the rest. I will merge it when ready.

**Pull request merged**
