### PR TITLE
Update Resources.uk-UA.resx

### PR DESCRIPTION
**Pull request by kaplun07**

### CODE REVIEW

**Comment by emoacht** [comment]
Thanks for supplementing.
I briefly checked translating to English.

- Regarding "Закрити программу", does the tooltip of close button in the title bar say so in Ukranian language of WIndows? I intend to use the same or equivalent wording of the OS's default ones.
- Regarding "Використовувати кольорову тему системи", ”тему систем” seems to mean system theme and if so, this wording is not correct. Accent color is not necessarily tied with a theme and it can be set independently. Could you reconsider it?

**Comment by kaplun07** [comment]
1. There are no tooltip. If you use "Close", it is mostly used in the sense of "close menu, window...". In Monitorian, the "Close" button is used to exit the program. Therefore, i added the translation "Close the program" [Закрити програму] to make it clearer. Maybe it's better to replace "Close" with "Exit" [Вийти] altogether.

2. It took 20 minutes to figure out what "Use accent color for brightness" does. The problem was that the default color was the same as the color that was in the Windows settings. (Windows - Settings - Personalization - Colors - Color theme.) Is it possible to set the color in some other way?

**Comment by emoacht** [comment]
I briefly checked Ukrainian language version of Windows 11.

1. I mean the tooltip when hovering the cursor over close button.
ukrainian-close-tooltip
It says "Закрити".
In fact, adding a word after "close" would not add much clarity because it still can be read as close this application's window. In the case of resident utilities like this app, there is no common expression to terminate it. I don't know "exit" is clearer. It may be the case in some languages but may not be in other languages.
After thinking about it long, I had come back to just "close", the most common word to terminate an app.

2. I found that in Windows settings of Ukrainian language version don't use the wordings equivalent to accent color.
ukrainian-accent-color
In English verson, the first line is "Choose your __accent color__" and the second is "Automatically pick an __accent color__ from my background". So I think the wording used in Ukrainian language version could be used.
Regarding "The problem was that the default color was the same as the color that was in the Windows settings.", I don't understand what is your point.

**Comment by emoacht** [comment]
1. Regarding "close", I don't rely much on what other third-party apps do. There is no definitive answer and I chose to use the same word as the OS does. So I will keep the current word.

2. It's a pity that the Ukrainian language of Windows does not describe the accent color clearly. Anyway, if a user is unaware of the accent color, it will be completely okay to leave the user to unaware.

**Pull request merged**
